version: '3.3'
services:
    nginx:
        image: 'artshellorok/nginx'
        restart: always
        ports:
            - '80:80'
        volumes: 
            - './dist:/usr/share/nginx/html'
            - './nginx/config:/etc/nginx'
    redis:
        image: 'artshellorok/redis'
        restart: always
    websocket:
        image: 'artshellorok/ws'
        restart: always
        ports:
            - '5000:5000'
        volumes:
            - './websocket/src:/srv/ws'
        links:
            - redis
        environment:
            - PORT=5000
            - TOKEN=b7037fe6b012ae49d6c8189b60ca2c0b3f820950b27881755d034a676d3680f5
